Revert "@`cxx/main.cxx`: -`assistantCnsTestsNoexcept`"
This reverts commit 350f9b452156256f9088c714facc509ac5d24f56.
<https://github.com/SwuduSusuwu/SusuLib/actions/runs/22463861653/job/65064944522> says [`assistantCnsTestsNoexcept()`](https://github.com/SwuduSusuwu/SusuLib/commit/5543de096c5dba0bda8754045adc33dae99ead6b) was stuck at:
	2026-02-26 22:29:53 (256 KB/s) - ‘downloads/index.html’ saved [432287]

	[./cxx/AssistantCns.cxx:100: Warning: assistantCnsDownloadHosts: { /* TODO: [deduce `ClassIoPath localDocumentSource;` from `classWebBrowseWget("https://stackoverflow.com", "");`](https://poe.com/s/QpjvvHmETSVP6K4wRiU5) */}]
	Error: The operation was canceled.

TODO: `./cxx/AssistantCns.cxx:assistantCnsDefaultHosts`: remove the host after "https://stackoverflow.com" (the above `stdout` suggests that the next host got stuck).