@`build.sh`; TensorFlow support improved
	+`SUSUWU_IS_VIRTUAL`, +`SUSUWU_INSTALL_TENSORFLOW`; flags to control `./build.sh`'s flow.
	+`export TF_CPP_MIN_LOG_LEVEL=0`; so TensorFlow debug messages are shown.
	If not `${USE_GOOGLEAPIS_TENSORFLOW}`, prefer `libtensorflow_cc` C++ package (which has system headers to use).
	`libeigen3-dev` search improved.
	Prefer system `libeigen3-dev`; fixes "tensorflow/core/framework/tensor.h:26:10: fatal error: /framework/tensor.h:26:10: fatal error:  unsupported/Eigen/CXX11/Tensor: No such file or directory" on Ubuntu.