@`cxx/AssistantCns.cxx`: response isa responses[0]
@`./cxx/AssistantCns.cxx`: use `std::remove_const`, so `response` isa `responses[0]`.
Is followup to: commit d7370e8fbb0e965757d1bca6acb82f71e1ed88fc (?`cxx/*.*x`: undo C++14 code, support `-std=c++11`), which introduces this.
TODO: @`./posts/VirusAnalysis.md`: include this.
TODO: ``AssistantCns.cxx:112:57: error: non-const lvalue reference to type 'std::string' cannot bind to a value of unrelated type 'const char[1]'`` solutions.