`--mingw`/`SUSUWU_WIN32` regression fix, typos fix
?`cxx/ClassSys.cxx`: `SUSUWU_WIN32` regression fix.
	`classSysHexStrTests`: `error: use of undeclared identifier 'SUSUWU_SH_0'` fix.
	Is followup to: e4dadb10bfd739062c5cc7e45c53e1120253f1df (?`classSysHexOs`: 2 hexits per char (logic fix):), which introduced +`classSysHexStrTests` (which caused the regression, due to use of `ERROR`).
	TODO: remove `ERROR` (since it conflicts with `#include <shlobj.h>` on _WIN32.) Is more complex than it sounds.

?`cxx/ClassResultList.cxx`: `clang-tidy` fix:
	`warning: #includes are not sorted properly [llvm-include-order]` fix.
	Is followup to: d7370e8fbb0e965757d1bca6acb82f71e1ed88fc (undo C++14 code, support `-std=c++11` ...+`#include <string>`).

?`build.sh`: typo fixes
	`:%s/"\`${SOURCE}\` is newer than \`${OBJECT}\`, will rebuild"/"\`${SOURCE}\` (which is a common `#include`) is newer than \`${OBJECT}\`, will rebuild"/`: message now gives reason that condition results in `--rebuild`.
	`:%s/intermediate objects+ continue/intermediate objects + continue/`: typo fix.
	Is followup to: 2a6e624025dd722a56a76f8164120a2cff886a19 (?`build.sh`: incremental builds (reuse objects),