@`cxx/main.cxx`: -`virusAnalysisTestsNoexcept`
@`./cxx/main.cxx:unitTestsCxx()`: do not process `virusAnalysisTestsNoexcept()` unless compiled with `-DSUSUWU_FORCE_VIRUS_ANALYSIS_TESTS`.
TODO: [learn the reason GitHub's `CodeQL-Build (c++)` workflows now get stuck after `classWebBrowseTestsNoexcept(): pass`](https://github.com/copilot/share/801f018e-40e0-8822-9152-e04800a36057).

Without this test disabled, <https://github.com/SwuduSusuwu/SusuLib/actions/runs/22458103954/job/65044685670> shows: `The job has exceeded the maximum workflow time of 6h0m0s`, plus the `Autobuild` section shows:
```
classWebBrowseTestsNoexcept(): pass
virusAnalysisTestsNoexcept():
Error: The operation was canceled.
```