@`cxx/main.cxx`: -`assistantCnsTestsNoexcept`
@`./cxx/main.cxx:unitTestsCxx()`: do not process `assistantCnsTestsNoexcept()` unless compiled with `-DSUSUWU_FORCE_ASSISTANT_CNS_ANALYSIS_TESTS`.
TODO: parse the reasons which prevent GitHub's workflows from successful execution of `assistantCnsTestsNoexcept()`

Without this test disabled, <https://github.com/SwuduSusuwu/SusuLib/actions/runs/.../job/...> shows: `The job has exceeded the maximum workflow time of 6h0m0s`, plus the `Autobuild` section shows:
	classWebBrowseTestsNoexcept(): pass
	virusAnalysisTestsNoexcept(): GitHub's workflow now stalls (was just a few seconds to execute, but now (for unknown reasons) is >6 hours to execute), use `-DSUSUWU_FORCE_VIRUS_ANALYSIS_TESTS` to enable thus
	assistantCnsTestsNoexcept():
	Error: The operation was canceled.

<https://github.com/SwuduSusuwu/SusuLib/actions/runs/22463861653/job/65064944522> says [`assistantCnsTestsNoexcept()`](https://github.com/SwuduSusuwu/SusuLib/commit/5543de096c5dba0bda8754045adc33dae99ead6b) was stuck at:
	2026-02-26 22:29:53 (256 KB/s) - ‘downloads/index.html’ saved [432287]

	[./cxx/AssistantCns.cxx:100: Warning: assistantCnsDownloadHosts: { /* TODO: [deduce `ClassIoPath localDocumentSource;` from `classWebBrowseWget("https://stackoverflow.com", "");`](https://poe.com/s/QpjvvHmETSVP6K4wRiU5) */}]
	Error: The operation was canceled.

TODO: `./cxx/AssistantCns.cxx:assistantCnsDefaultHosts`: remove the host after "https://stackoverflow.com" (the above `stdout` suggests that the next host got stuck).