@`cxx/main.cxx`: -`classTensorFlowCnsTestsNoexcept`
@`./cxx/main.cxx:unitTestsCxx()`: do not process `classTensorFlowCnsTestsNoexcept()` unless compiled with `-DSUSUWU_FORCE_CLASS_TENSORFLOW_CNS_ANALYSIS_TESTS`.
TODO: [learn the reason GitHub's `CodeQL-Build (c++)` workflows now get stuck after `classWebBrowseTestsNoexcept(): pass`](https://github.com/copilot/share/801f018e-40e0-8822-9152-e04800a36057) <https://github.com/orgs/community/discussions/188055>
------
Without this test disabled, <https://github.com/SwuduSusuwu/SusuLib/actions/runs/22456561518/job/65039226222> shows: `The job has exceeded the maximum workflow time of 6h0m0s`, plus the `Autobuild` section shows:
```
  classTensorFlowCnsTestsNoexcept2026-02-26 18:58:03.266840: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
  Error: The operation was canceled.
```