@`SUSUWU_INCLUDES_LIBTENSORFLOW()`: improved
@`sh/Includes.sh:SUSUWU_INCLUDES_LIBTENSORFLOW()`:
	+`export TF_CPP_MIN_LOG_LEVEL=0`; so TensorFlow debug messages are shown.
	If not `${USE_GOOGLEAPIS_TENSORFLOW}`, prefer `libtensorflow_cc` C++ package (which has system headers to use).
	`libeigen3-dev` search improved.
	Prefer system `libeigen3-dev`; fixes "tensorflow/core/framework/tensor.h:26:10: fatal error: /framework/tensor.h:26:10: fatal error:  unsupported/Eigen/CXX11/Tensor: No such file or directory" on Ubuntu.
	Is followup to: commit HEAD~2 (+`sh/Includes.sh:SUSUWU_INCLUDES_LIBTENSORFLOW()`). TODO: `squash`?

@`build.sh`:
	@`SUSUWU_IS_VIRTUAL`: improved.
	@`SUSUWU_INSTALL_TENSORFLOW`: moved to `sh/Includes.sh:SUSUWU_INCLUDES_LIBTENSORFLOW()`.
	Is followup to: commit HEAD~1 (+`SUSUWU_IS_VIRTUAL`, +`SUSUWU_INSTALL_TENSORFLOW`). TODO: `squash`?